- yara_/Dockerfile
As mentioned in #4.  Also updates to YARA 4.0.2, the latest release.
> Clearer YARA version tracking

- yara_/yara_.py
- yara_/yara_updater.py
Implementation; relating to [Signature sources: Add support for adding certificate](https://cccs.atlassian.net/browse/AL-842)
> Updater considers CA cert and ignore SSL flags before session init

- yara_/yara_updater.py
Depending on the signatures, it seems to take longer to index them into the ES. Queries to download the signatures sometimes return a non-zip type.
Adding a timeout of 30s seems to resolve it in dev after the first attempt. Adding up to 5 attempts: if all fail, log error to check sources.
Phenomenon has only happened with YARA so far, but potentially could happen with any service using an updater.
> Add chances for updater to download signatures to disk

- yara_/yara_updater.py
Requires these PRs to be merged/used:
https://github.com/CybercentreCanada/assemblyline-ui/pull/38
https://github.com/CybercentreCanada/assemblyline-base/pull/48
> Add proxy support in signature updater

- yara_/yara_updater.py
Change required to allow updaters to reach their sources within LS Rancher (worth testing in staging)
> Modify proxy usage k8s

- yara_/Dockerfile
Replicate the some Dockerfile lines used in CCCS-YARA-Feeds to enable validation of signatures using the dotnet library:
https://github.com/CybercentreCanada/CCCS-Yara-Feeds/blob/master/Dockerfile
> Enable dotnet module

- yara_/Dockerfile
Related to: https://cccs.atlassian.net/browse/AL-1162
> Update yara to 4.1.0

- yara_/Dockerfile
- yara_/helper.py
- yara_/yara_.py
Interim fix for: https://cccs.atlassian.net/browse/AL-1659
Pending PR: https://github.com/VirusTotal/yara-python/pull/201
> Switch yara-python to fork

- yara_/service_manifest.yml
Addressing: https://discord.com/channels/908084610158714900/908084610624274494/964188266360373278
> Update default sources to use better ruleset

- yara_/yara_.py
Modified to accept StringMatch objects returned by YARA 4.3.0.
https://github.com/VirusTotal/yara-python/releases/tag/v4.3.0
> Accept YARA 4.3.0 Matches

- tagcheck/service_manifest.yml
- tagcheck/update_server.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/84
> Fix TagCheck patterns

- yara_/yara_.py
Depends on: https://github.com/CybercentreCanada/assemblyline-v4-service/pull/638
> Use signature meta from updater for results

- yara_/helper.py
- yara_/service_manifest.yml
Depends on: https://github.com/CybercentreCanada/assemblyline-v4-service/pull/645
> Update synchronicity code to let client handle it

- yara_/helper.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/142
> If a null version is extracted, go back to default

- .vscode/settings.json
- yara_/helper.py
- yara_/update_server.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/152
\+ black formatting
> Add "r" to STRING_ESCAPE_CHARS in plyara

- yara_/service_manifest.yml
- yara_/update_server.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/158
> Fix bug with arbitrary "include" strings in rules

- yara_/Dockerfile
Related to: https://github.com/CybercentreCanada/assemblyline/issues/231
Related PR: https://github.com/plyara/plyara/pull/130
> Use fork of plyara that support parsing negative values

- tagcheck/rules/tagcheck.rules
Addresses https://cccs.atlassian.net/browse/AL-3120
> Adding rules from CAPE's sig repo

- tagcheck/service_manifest.yml
Related to: https://github.com/CybercentreCanada/assemblyline/issues/265
> Update service_manifest.yml to use latest TagCheck rules

- .devcontainer/devcontainer.json
- tagcheck/service_manifest.yml
- yara_/yara_.py
Related to: https://github.com/CybercentreCanada/assemblyline/issues/352
> Remove unnecessary file requirement from TagCheck
